# --- Network ---
bind 0.0.0.0
port 6239
tcp-backlog 511
timeout 300
subscribed_timeout 3600

# --- Limits & Resources ---
# Максимальное число клиентов
maxclients 10000
# Лимит памяти (0 - без лимита)
maxmemory 536870912
# Частота работы фоновых задач (Cleaner) в Гц
hz 10